spring.application.name=StorageService

minio.idKey=${ID_KEY:dummy-key}
minio.secretKey=${SECRET_KEY:dummy-secret}
minio.endpoint=http://minio-server:9000
minio.region=ru-central1
minio.bucket=my-bucket

metadata.service.url=http://metadata-service-app:8081

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=DEBUG
