spring.application.name=RegistrationProcess

server.port=8082

spring.data.redis.host=redis
spring.data.redis.port=6379

metadata.service.url=http://metadata-service-app:8081
storage.service.url=http://storage-service-app:8080

